trashemail:
  host: localhost
  port: 9090
  path: /getChatId/

imap-client-service:
  telegram:
    url: https://api.telegram.org/bot
    bot-token: xxx
    size: 4096
  imap:
    host: trashemail.in
    port: 993
    emails:
      - contact@trashemail.in
      - contact2@trashemail.in
      - contact3@trashemail.in
    passwords:
      - changeme
      - changeme
      - changeme
  emails:
    hostPath: http://192.168.225.39:8000/
    downloadPath: /tmp/


spring:
  application:
    name: EmailsToTelegramService
  main:
    web-application-type: none


logging:
  level:
    io:
      github:
        trashemail: debug